#include<iostream>
#include<windows.h>
using namespace std;
int main()
{
	cout<<"Part 1"<<endl<<endl;
	Sleep(200);
	cout<<"程序的指针 变野了"<<endl;
	Sleep(200);
	cout<<"而我却变得 单身了"<<endl;
	Sleep(200);
	cout<<"指针指向的 不再是对象"<<endl;
	Sleep(200);
	cout<<"而是指向了 一个虚无缥缈的内存空间"<<endl;
	Sleep(200);
	cout<<"一个野指针 没有一丁点用处"<<endl;
	Sleep(200);
	cout<<"但是 它却在系统指定分配的内存空间里面"<<endl;
	Sleep(200);
	cout<<"直到……"<<endl;
	Sleep(200);
	cout<<"程序关闭 当程序的函数返回0的时候"<<endl;
	Sleep(200);
	cout<<"这个野指针 将不再是指针"<<endl;
	Sleep(200);
	cout<<"而我却轻声告别这新生的黎明."<<endl;
	Sleep(1000);
	cout<<""<<endl<<endl<<endl;
	Sleep(200);
	cout<<"Part 2"<<endl<<endl;
	Sleep(200);
	cout<<"程序员不需要对象"<<endl;
	Sleep(200);
	cout<<"程序员不配拥有对象."<<endl;
	Sleep(200);
	cout<<"人们说，程序员要面向对象"<<endl;
	Sleep(200);
	cout<<"但是程序员哪里有对象."<<endl;
	Sleep(200);
	cout<<"程序员面对的是一堆bug罢了"<<endl;
	Sleep(200);
	cout<<"一堆永远改不完的bug罢了."<<endl;
	Sleep(200);
	cout<<"IDE里，跳动的字符"<<endl;
	Sleep(200);
	cout<<"这让每个程序员想起了自己给电脑写的第一句话：hello world！"<<endl;
	Sleep(200);
	cout<<"电脑开始编译你写的程序……"<<endl;
	Sleep(200);
	cout<<"提示框里 弹出了几十个错误提醒"<<endl;
	Sleep(200);
	cout<<"你开始动用你仅有的学识"<<endl;
	Sleep(200);
	cout<<"把代码错误全部补上"<<endl;
	Sleep(200);
	cout<<"改语法 改数据 "<<endl;
	Sleep(200);
	cout<<"什么都要改"<<endl;
	Sleep(200);
	cout<<"待到程序可以正常运行"<<endl;
	Sleep(200);
	cout<<"你又会发现……"<<endl;
	Sleep(200);
	cout<<"程序有大量bug"<<endl;
	Sleep(200);
	cout<<"不是短时间内可以解决的"<<endl;
	Sleep(200);
	cout<<"可是甲方爸爸正在催工程"<<endl;
	Sleep(200);
	cout<<"你不得不以极高的工作强度继续工作下去"<<endl;
	Sleep(200);
	cout<<"一杯咖啡"<<endl;
	Sleep(200);
	cout<<"一台电脑"<<endl;
	Sleep(200);
	cout<<"一盏台灯"<<endl;
	Sleep(200);
	cout<<"一个晚上"<<endl;
	Sleep(200);
	cout<<"一个人 "<<endl;
	Sleep(200);
	cout<<"创造着一个逐渐完美的程序."<<endl;
	Sleep(500);
	cout<<"——献给如我们一般的程序员      by coder_fanjun";
	} 
